name: deploy to ipfs gateway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - name: deploy the thing
        env:
          IPFS_DEPLOY_PINATA__API_KEY: 8dc9dcf2b277df8553ee
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: 320colab.space
          IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.stems.320colab.space
        run: |
          npm run deploy-site